
# Load objects  ---------------------------------------------------------------------------------------------------
make_panel <- function(comp = "Btotal") {
  
names <-  output_dir %>%
  list.files %>%
  tools::file_path_sans_ext()

models <-
  output_dir %>%  list.files(full.names = TRUE) %>% map(readRDS) %>%  set_names(names)



#Rank variables by effect size ---------------

order <- 
  models %>%
  #access the first iteration and extract the curves for the beta total component
  pluck("Null_BBGDM_1", "coefficient", comp) %>% 
  arrange(desc(effect_size)) %>% 
  rownames_to_column("var") %>%
  select("var") %>% 
  mutate(var = factor(var, levels=var)) %>% 
  mutate(var = recode_factor( var,  
                              development = "Development\n[m]",
                              elev = "Elevation\n[m]",
                              entranceSize="Entrance\nsize [m²]",
                              Geographic="Geographic\ndistance [km]",
                              ice="LGM ice\ndistance [km]",
                              karst="Karst\narea [km²]",
                              negativeDrop="Negative\ndrop [m]",
                              annual_range="Annual range\n[ºC]",
                              prec="Precipitation\n[mm]",
                              T_mean="Temperature\n[ºC]")) %>%  pull(var)

# Get curves for original variables (Panel 1) ---------------------------------------------------------------------

panel_1 <- models %>%
  #access the first iteration and extract the curves for the beta total component
  pluck("Null_BBGDM_1", "curves", comp) %>%
  mutate(variable = recode_factor( variable,  
                                   development = "Development\n[m]",
                                   elev = "Elevation\n[m]",
                                   entranceSize="Entrance\nsize [m²]",
                                   Geographic="Geographic\ndistance [km]",
                                   ice="LGM ice\ndistance [km]",
                                   karst="Karst\narea [km²]",
                                   negativeDrop="Negative\ndrop [m]",
                                   annual_range="Annual range\n[ºC]",
                                   prec="Precipitation\n[mm]",
                                   T_mean="Temperature\n[ºC]"
  )) %>% 
  mutate(variable = factor(variable, levels=order)
  )  %>% 
  #plot the mean value of the splines
  ggplot(aes(value, X50.)) +
  geom_line() +
  #plot the error
  geom_ribbon(aes(ymin=X5., ymax=X95.), alpha=.2) +
  #split plot by variable but allow only a single column
  facet_wrap( ~ variable, scale = "free", ncol = 1)  +
  theme_classic() +
  theme(strip.text = element_blank(),
        axis.text = element_text(size= 12),
        axis.title = element_text(size=14), 
        plot.background = element_rect(fill=NA, colour= NA),
        panel.background = element_rect(fill = NA, colour = NA ))+
  scale_y_continuous(breaks=breaks_extended(4))


# Object to plot histogram ( panel 2 ) ----------------------------------------------------------------------------

Null_coef <- models %>%
  #map over each iteration (first level of the list)
  map(~ .x %>% 
        #within each iteration, extract the coefficient data ( second level of the list)
        pluck("coefficient") 
  ) %>%
  #transpose the list such that the beta diversity component becomes the first level of the list
  purrr::transpose() %>%
  #map over each beta diversity component (current first level of the list) 
  map(
    ~ .x %>%
      #additional mapping to go through each iteration again    
      map( ~ .x %>% 
             #convert coefficient information into data frame
             data.frame %>%
             #convert row names into columns (this is actually the variables name)
             rownames_to_column("var")   
      ) %>%
      #remove empy objects (these were generated by failed runs in the super computer)
      compact %>%
      #combine second-order lists and import names to identify each iteration
      bind_rows(.id = "iteration")
  ) %>%
  #combine first-order lists and import names to identify each beta diversity component
  bind_rows(.id = "Component") %>%
  #remove variables generated by failed runs 
  filter(var != 1) %>%
  #keep only beta diversity component, variables and effect size (i.e., sum of spline coefficients)
  #select(Component, var, effect_size) %>% 
  #rename column "effect_size" to "coefficient" to not confound with the effect size estimated afterwards
  rename(coefficient  = "effect_size") %>% 
  group_by(Component, var) %>% 
  add_count(coefficient) %>% 
  ungroup()  %>% 
  mutate(var = recode_factor( var,  
                              development = "Development\n[m]",
                              elev = "Elevation\n[m]",
                              entranceSize="Entrance\nsize [m²]",
                              Geographic="Geographic\ndistance [km]",
                              ice="LGM ice\ndistance [km]",
                              karst="Karst\narea [km²]",
                              negativeDrop="Negative\ndrop [m]",
                              annual_range="Annual range\n[ºC]",
                              prec="Precipitation\n[mm]",
                              T_mean="Temperature\n[ºC]"
  )) %>% 
  mutate(var = factor(var, levels=order))



ES_p_value <- #create object for p_values of the null distribution (non-parametric)
  Null_coef %>%
  #divide object into lists based on the beta diversity component 
  split(f = as.factor(.$Component)) %>%
  #go through each beta diversity component (first level list)
  map( ~ .x %>%
         #divide the objects within each beta diversity component into lists based on variable name
         split(f = as.factor(.$var)) %>%
         #go trhough each variable object (second level list) to estimate effect size (SE) and p value of the null distribution
         map(
           ~ data.frame(
             value = BAT::ses(
               obs = .x$coefficient[1], #here we select only the value for actual trait composition
               est = .x$coefficient[-1], #here we select the values for null trait composition (999 runs)
               param = FALSE #set this to TRUE to gave a parametric SES estimation
             )
           ) %>%
             #row names are the SES and p value, convert it into a column called "Metric"
             rownames_to_column("Metric")
         )) %>%
  # go trough each variable object (second level list) and combine into a data frame 
  # import name to identify the variables (.id  = var)
  map(~ bind_rows(.x, .id = "var")) %>%
  #combine the beta diversity components (first level list) into a single data frame
  #import name to identify the components (.id = "Component")
  bind_rows(.id = "Component") %>%
  #spread the column "metric" into two new columns (SES, p_value)
  pivot_wider(names_from = Metric, values_from = value) %>%
  #rename column "p-value"
  rename(p = "p-value") %>% 
  full_join(
    #add observed values
    Null_coef %>%
      filter(iteration %in% "Null_BBGDM_1") %>% 
      select(-.) 
  ) %>%   mutate(var = recode_factor( var,  
                                      development = "Development\n[m]",
                                      elev = "Elevation\n[m]",
                                      entranceSize="Entrance\nsize [m²]",
                                      Geographic="Geographic\ndistance [km]",
                                      ice="LGM ice\ndistance [km]",
                                      karst="Karst\narea [km²]",
                                      negativeDrop="Negative\ndrop [m]",
                                      annual_range="Annual range\n[ºC]",
                                      prec="Precipitation\n[mm]",
                                      T_mean="Temperature\n[ºC]"
  )) %>% 
  mutate(var = factor(var, levels=order))

panel_2<- 
  Null_coef %>%
  filter(Component %in% comp) %>%
  ggplot(aes(x = coefficient)) +
  geom_histogram(fill="gray10") +
  geom_segment(
    data = ES_p_value %>% filter(Component %in% comp),
    aes(x = coefficient, xend = coefficient, y = 0, yend=250, colour=p > 0.975),
    linetype = 1
  ) +
  geom_point(
    data = ES_p_value %>% filter(Component %in% comp),
    aes(x = coefficient,y=250, colour = p>0.975)
  ) +
  geom_text_npc(data = ES_p_value %>% filter(Component %in% comp),
                aes(
                  npcx = .5,
                  npcy = .95,
                  label = glue::glue("SES = {round(ses,3)}\n p-value = {round(p,3)}")
                ), size=4, hjust=0) +
  facet_wrap( ~ var, scale = "free_x", ncol = 1, shrink=TRUE, strip.position="right")  +
  theme_classic()+
  theme(strip.text = element_blank(),
        legend.position="none",
        axis.text = element_text(size= 12),
        axis.title = element_text(size=14),
        plot.background = element_rect(fill=NA, colour= NA),
        panel.background = element_rect(fill = NA, colour = NA)) +
  scale_y_continuous(breaks=breaks_extended(3), limits=c(0,500))+
  scale_colour_manual(values= rev(c(plot_colour, colorspace::lighten(plot_colour,.6))))

models %>%
  #access the first iteration and extract the curves for the beta total component
  pluck("Null_BBGDM_1", "curves", "Btotal") %>% 
  distinct(variable)

Null_curves <-
  models %>%
  map( ~ .x %>%  pluck("curves")) %>%
  purrr::transpose() %>%
  map(
    ~ .x %>%
      map(~ .x %>% data.frame) %>%
      compact %>%
      bind_rows(.id = "iteration") %>%
      group_by(variable, iteration) %>%
      mutate(code = row_number(value)) %>%
      ungroup()
  ) %>%
  map(
    ~ .x %>%
      split(f = as.factor(.$variable)) %>%
      #variable list
      map(
        ~ .x %>%
          split(f = as.factor(.$code)) %>%
          #code list
          map(
            ~ rbind(ses_tidy(.x, "X5."),
                    ses_tidy(.x, "X50."),
                    ses_tidy(.x, "X95.")) %>%
              rownames_to_column("metric")
          ) %>%
          bind_rows(.id = "code")
      ) %>%
      #variable list
      bind_rows(.id = "variable")
  ) %>%
  #Component list
  bind_rows(.id = "component")  %>%
  pivot_wider(names_from = metric, values_from = value) %>%
  mutate(code = as.numeric(code)) %>%
  full_join(
    models %>%
      pluck(1, "curves", 1) %>%
      group_by(variable) %>%
      mutate(code = row_number(value)) %>%
      ungroup() %>%
      select(value, code, variable)) %>% 
  mutate(variable = recode_factor( variable,  
                                   development = "Development\n[m]",
                                   elev = "Elevation\n[m]",
                                   entranceSize="Entrance\nsize [m²]",
                                   Geographic="Geographic\ndistance [km]",
                                   ice="LGM ice\ndistance [km]",
                                   karst="Karst\narea [km²]",
                                   negativeDrop="Negative\ndrop [m]",
                                   annual_range="Annual range\n[ºC]",
                                   prec="Precipitation\n[mm]",
                                   T_mean="Temperature\n[ºC]"
  )) %>% 
  mutate(variable = factor(variable, levels=order))



panel_3 <- Null_curves %>%
  filter(component == comp, code > 1) %>%
  mutate(signif =case_when(p_X50. < 0.025 ~ "Underdispersion",
                           p_X50. > .975 ~ "Overdispersion" , TRUE ~ "Random")) %>% 
  ggplot(aes(
    x = value,
    y = SES_X50.,
  )) +
  geom_line(size=2,colour = plot_colour) +
  gghighlight(if_any(p_X50.) > .975,
              unhighlighted_params = list(colour = colorspace::lighten(plot_colour,.8), size=2))+
  
  facet_wrap(
    ~ variable,
    scale = "free_x",
    ncol = 1,
    shrink = TRUE,
    strip.position = "right"
  )  +
  theme_classic() +
  scale_linetype_manual("Significant",
                        values = c(1, 2),
                        labels = c("True", "False")) +
  theme(legend.position = "bottom",
        strip.text = element_text(face = "bold", size = 12),
        axis.text = element_text(size= 12),
        axis.title= element_text(size=14)) +
  scale_y_continuous(breaks = breaks_extended(3)) 


figure<- (panel_1 + labs(y="Change in Beta diversity",x="Gradient") + 
              panel_2 + labs(y="Counts", x = "Total change in beta diversity")  +
              panel_3 + labs(y="Standardized effect size (SES)",x="Gradient")+
              plot_annotation(tag_level = "a") ) & 
  theme(plot.tag = element_text(face="bold"))


ggsave(figure, filename=paste0("Results/",comp,".pdf"), height=17, width=11, device=cairo_pdf)

       }
